# Generated by Django 3.0.5 on 2021-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200427_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
